POST  http://localhost:3000/api/login
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nzk1LCJ0ZWFtSWQiOiIxNC02IiwiaWF0IjoxNzQ5MTMxMjEwLCJpc3MiOiJzcC1tb2dhem9hIn0.iOdEEyzyJ59bQ49RSWaD27DNVF2j1aIYExCsIyVTSV8"
}


GET http://localhost:3000/api/cookie
x-csrf-token: 1f6ff74dbb1dcb2985a815ee0fc2a5de56200ffd1a7229685ca86b17da9f3370
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Nzk1LCJ0ZWFtSWQiOiIxNC02IiwiaWF0IjoxNzQ5MTMxMjEwLCJpc3MiOiJzcC1tb2dhem9hIn0.iOdEEyzyJ59bQ49RSWaD27DNVF2j1aIYExCsIyVTSV8; csrf-token=1f6ff74dbb1dcb2985a815ee0fc2a5de56200ffd1a7229685ca86b17da9f3370
