import type { Metadata } from "next";
import { M_PLUS_Rounded_1c } from "next/font/google";
import "./globals.css";
import QueryProvider from "./providers/QueryProvider";

const mplus = M_PLUS_Rounded_1c({
  variable: "--font-mplus",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
<<<<<<< HEAD
=======

>>>>>>> 0594f1cfb52c09a290bb15bd766b5cd54f5510ab
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
<<<<<<< HEAD
=======


>>>>>>> 0594f1cfb52c09a290bb15bd766b5cd54f5510ab
      <body className={`${mplus.variable} antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
